# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uT_I60hb9tg5jRVj7topPb847FtkP7HA
"""



"""OPERACION PROMEDIO"""



from posixpath import realpath
#INGRESAR LA TRES NOTAS
n1 = int(input("INGRESE EL PRIMER NUMERO: "))
n2 = int(input("INGRESE EL SEGUNDO NUMERO: "))
n3 = int(input("INGRESE EL TERCER NUMERO: "))
#OPERACION PROMEDIO
suma = n1 + n2 + n3
promedio = suma /3

print ("El promedio de las notas es: ", promedio)

if promedio >= 11:
    mje = "Aprobó"
else:
    mje = "Desaprobó"

print(mje)